CC = g++
CFLAGS = -Wall -g
 
partA: 
    $(CC) $(CFLAGS) -o partA partA.o
 
partA.o:  
    $(CC) $(CFLAGS) -c $(PARTA).cpp

partB:
    $(CC) $(CFLAGS) -o partB.o 

partA.o:  
    $(CC) $(CFLAGS) -c $(PARTB).cpp
